# Generated by Django 5.0.7 on 2024-08-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_bank_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_type',
        ),
    ]
