# Generated by Django 5.0.7 on 2024-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_bank_bank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='game_id',
            field=models.TextField(verbose_name='Game_ID'),
        ),
    ]
